### ISSUE TITLE
Proxying with other user

### ISSUE THREAD

**Issue by CarlosCordoba96** [tsurubee/sshr#34]
I am trying to proxy to another ssh server but not using the user used in the ssh command, my idea is to use the function to query with the user the server i want, but that other server have another user, for example root. The problem that when i try to enter the server it gives me an error. 
How could i do to change the user i send to the proxied server?

The idea is:
i execute:
ssh server1@proxyserver -p 2222 

Proxy: server1   forward to -> server: privateserverip user:root

I dont know if this could be done.

**Comment by CarlosCordoba96** [comment]
@tsurubee

**Comment by tsurubee** [comment]
@CarlosCordoba96 Thank you for your question!
I'm sorry, but I didn't understand what you wanted to do.

In the current sshr, the user name used by the client in the ssh command is used by the sshr server (=proxy server) to send a connection request to the destination SSH server.  Is this the answer you want?

**Comment by CarlosCordoba96** [comment]
Hi, thanks for the reply, and sorry for not explaining correctly, My question is, how sshr could send to the destination server the connection request with another user  readed from a file or db like in the method You take the host direction depending on the user.

**Comment by tsurubee** [comment]
I don't understand this part "with another user readed from a file or db".
sshr does not read the user from a file or DB, but reads the destination server using the client's user name as a key.
Then, it sends an SSH request based on the user name received from the client and the destination server read from the a file or DB.

**Comment by CarlosCordoba96** [comment]
Sorry for not expressing myself correctly, the idea I have is to modify part of the sshr code, to take advantage of the FindUpstreamHook function to return not only the host, but also the possibility of returning somehow this data: "user@host:port", parse it later in the proxy.go file, but of course, I do not know if from the proxy.go file I can modify the user with which it is authenticated in the new host.

**Comment by tsurubee** [comment]
I think I understand what you're trying to do.
Unfortunately, sshr cannot modify the user used to authenticate to new host.
However, I think it is possible in principle to implement what you want to do.
